name: Check PR
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Go Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
          cache: false

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: latest
          args: --verbose

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

      - name: goreleaser check
        uses: goreleaser/goreleaser-action@v4.3.0
        with:
          args: check
